language: python            # this works for Linux but is an error on macOS or Windows
matrix:
  include:
    - os: windows
    - language: shell
    - python: 3.7
before_install:
  - python --version
  - python -m pip install --upgrade pip
  - pip3 install --upgrade pytest
  - pip3 install codecov
install:
    - pip install -r requirements.txt
script:
    - python test_ArimaModelGui.py
