language: shell
matrix:
  include:
    - os: windows
    - language: shell
    - python: 3.7
before_install:
  - python --version
  - pip install -U pip
  - pip install -U pytest
  - pip install codecov
install:
  - pip install -r requirements.txt
script: python test_ArimaModelGui.py # run tests
after_success:
  - codecov # submit coverage
