language: python
matrix:
  include:
    - python: 3.7
    - os: windows
    - language: shell
before_install:
  - python --version
  - pip install -U pip
  - pip install -U pytest
  - pip install codecov
install:
  - pip install -r requirements.txt
script: pytest # run tests
after_success:
  - codecov # submit coverage
