language: python
matrix:
  include:
    - name: "Python 3.5.4 on Windows"
      os: windows
      language: shell
      python: "3.7"
      before_install:
        - choco install python --version 3.5.4
        - python --version
        - python -m pip install --upgrade pip
        - pip3 install --upgrade pytest
        - pip3 install codecov
        env: PATH="/c/Python37:/c/Python37/Scripts:$PATH"
install:
    - pip install -r requirements.txt

script: pytest
