language: python            # this works for Linux but is an error on macOS or Windows
jobs:
  include:
    - name: "Python 3.7.4 on Windows"
      os: windows           # Windows 10.0.17134 N/A Build 17134
      language: shell       # 'language: python' is an error on Travis CI Windows
      before_install:
        - choco install python --version 3.8.0
        - python -m pip install --upgrade pip
        - python -m pip install -r requirements.txt
      env: PATH=/c/Python38:/c/Python38/Scripts:$PATH
install:
  - pip3 install codecov
  - pip3 install --upgrade pip
  - pip3 install -r requirements.txt

services:
  - mysql
# all three OSes agree about 'pip3'
# 'python' points to Python 2.7 on macOS but points to Python 3.7 on Linux and Windows
# 'python3' is a 'command not found' error on Windows but 'py' works on Windows only
script:
  - coverage run -m unittest discover -v
  #- pytest .\test_ArimaModelGui.py

after_success:
  - bash <(curl -s https://codecov.io/bash)
