language: python
matrix:
  - os: windows
    language: 3.6
    before_install:
    - choco install python3
    - export PATH="/c/Python37:/c/Python37/Scripts:$PATH"
    - python --version
    - pip install -U pip
    - pip install -U pytest
    - pip install codecov

install: pip install -r requirements.txt

script: pytest
