language: python            # this works for Linux but is an error on macOS or Windows
python:
  - 3.7
before_install:
  - python --version
  - pip install -U pip # because you always have to work with the most updated pip. Some builds will fail without this
  - pip install -U pytest
  - pip install codecov
  - QT_QPA_PLATFORM=minimal go test -v -race
install:
    - pip install -r requirements.txt
script:
    - python test_ArimaModelGui.py
after_success:
  - codecov # submit coverage
