language: shell
matrix:
  include:
    - name: "Python 3.5.4 on Windows"
      os: windows           # Windows 10.0.17134 N/A Build 17134
      language: shell       # 'language: python' is an error on Travis CI Windows
      before_install:
        - choco install python --version 3.5.4
        - python --version
        - python -m pip install --upgrade pip
        - pip3 install --upgrade pytest
        - pip3 install codecov
      env: PATH=/c/Python35:/c/Python35/Scripts:$PATH
      install:
        - pip install -r requirements.txt
        script:
          - pytest


#language: python            # this works for Linux but is an error on macOS or Windows
#python:
#  - 3.6
#before_install:
#  - python --version
#  - pip install -U pip # because you always have to work with the most updated pip. Some builds will fail without this
#  - pip install -U pytest
#  - pip install codecov
